HISTORY.rst
cattr/__init__.py
cattr/_compat.py
cattr/converters.py
cattr/function_dispatch.py
cattr/multistrategy_dispatch.py
docs/structuring.rst
setup.py
tests/metadata/test_roundtrips.py
tests/test_function_dispatch.py
tests/test_multistrategy_dispatch.py
tests/test_structure.py
tests/test_unstructure.py
tox.ini

This address #9.
A proof of concept PR, so I could do more polish on it. But it illustrates:
1. using a FunctionDispatch class vs SingleDispatch.
2. feature parity with SingleDispatch (including caching for quick lookup)
Tried it out locally, works with py27 and py36, sans the vendor typing library.
More improvements / changes:
- change the register function signature to take two functions, rather than type + function.
- use FunctionDispatch to also handle attrs

adding a function based dispatch.

---

cattr/converters.py
tests/metadata/test_roundtrips.py
tests/test_structure_attrs.py

These changes are to fix #10 or #14 
I added one unit test to support creating the attr class without providing optional value. 
@Tinche let me know your feedback on the same.

Support to respect default values from attr class

---

setup.cfg

Without this directive it is not included: wheels ignore MANIFEST.in
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

Ensure that LICENSE is included in the built wheel

---

tests/test_structure.py
tests/test_unstructure.py

`hypothesis.strategies.choices` was deprecated in `v3.15.0` and removed in `v4.0.0`, see the [changelog](https://hypothesis.readthedocs.io/en/latest/changes.html#v4-0-0). This PR fixes the failing tests suite.
Please verify that I've done this correctly, I've never used `hypothesis` before.

Fix hypothesis `choices` removal

---

CONTRIBUTING.rst
docs/structuring.rst
src/cattr/_compat.py
src/cattr/generation.py
tests/__init__.py
tests/conftest.py

Fix test_unmodified_generated_unstructuring test
This was broken for 3.7 due to how `cattr.generation.make_dict_unstructure_fn`
reaches directly into `converter._unstructure_func.dispatch` to get the
converter function passing the annotated type of the field. In 3.7 the
`TypeError: Subscripted generics cannot be used with class and instance checks`
issue causes the `dispatch` to be the fallback identity converter func.
Normal usage (i.e. unstructure_attrs_asdict) passes in field_inst.__class__
which would never hit the above `TypeError` so this issue is unique to
`make_dict_unstructure_fn`

Fix master build

---

README.rst

This is the 'python console' lexer in pygments, which is intended for use with `>>>` REPL sessions. It should look better on PyPI on next release.

Use pycon highlighting in README

---

setup.py

Check https://packaging.python.org/guides/dropping-older-python-versions/ for more details
The latest cattrs 1.1.0 removed support for Python 3.6 but it since most of the libraries like Airflow (I am the maintainer and PMC Member of the Airflow Project) have an open bound for cattrs in the dependency, new users trying to setup airflow breaks (Issue: https://github.com/apache/airflow/issues/11965).
Setting an explicit `python_requires` means Python 3.6 users won't be able to download the new cattrs version and fallback to the older version that supports Python 3.6 and hence it will work without breaking Airflow too.
Thanks for creating and maintaining this library, appreciate all your effort, hope this PR is useful

Set Explicit requirement for Python>=3.7

---

src/cattr/converters.py

A generic structure hook is expected to return a value of the type that it accepts as an argument.
I feel guilty submitting a two-byte PR but I noticed that there aren't any tests that invoke mypy. Would it be useful to do some type checking as part of the test suite?
Closes #106.

Fix signature for generic structure hooks

---

HISTORY.rst
src/cattr/disambiguators.py
tests/test_disambigutors.py
tests/test_structure.py

Structure union of attr classes when one of the fields was optional and had a default value was not deterministic.
Disambiguator function sometimes was created to use field with default value - and because it's allowed to not provide this value to `__init__` method wrong class was chosen to structure.
A provided test case is a minimal deterministic test I was able to generate.

fix structure for union of attr classes with default values

---

HISTORY.rst
docs/customizing.rst
docs/index.rst
docs/unions.rst
src/cattr/_compat.py
src/cattr/converters.py
src/cattr/function_dispatch.py
src/cattr/gen.py
src/cattr/multistrategy_dispatch.py
tests/metadata/test_genconverter.py
tests/metadata/test_roundtrips.py
tests/test_unions.py

Flesh out our union support, for a start.

Better unions

---

HISTORY.rst
src/cattr/converters.py
src/cattr/multistrategy_dispatch.py
tests/test_genconverter_inheritance.py

Because the GenConverter specifically handles generating code for
attrs classes, and because it registers hooks that don't require
function dispatch, singledispatch was preventing subclasses from
having code generated for them, because they would trigger the
previously-generated base class's structure/unstructure code.
This changes MultiStrategyDispatch to allow for a class-based hook to
specifically avoid single-dispatch. Since we know that a given attrs
class can always have code generated for it, we don't really want to
share dispatch across subclasses - like the original Converter, we
want to make sure we're structuring each individual attrs class as its
own separate type.
fixes #116

fix MultiStrategyDispatch to work with new GenConverter and attrs inheritance

---

HISTORY.rst
docs/customizing.rst
src/cattr/converters.py
src/cattr/gen.py
tests/metadata/test_genconverter.py

Would resolve #101.  I'm assuming this will need some further work (e.g. new tests; fixing other tests this breaks, etc), but wanted to go ahead and get it up for a first review to see if the approach is reasonable.

Forbid extra fields when structuring dictionaries into attrs classes

---

pyproject.toml

The incompatible change seems to have been introduced in 1.1.0 (in https://github.com/Tinche/cattrs/pull/98) and we cannot fix those packages retroactively but we can at least mark it going forward.

Mark as requiring Python 3.7 and higher

---

pyproject.toml

This should make checking for changes in new versions more easy when coming form PyPI. The names where chosen as in attrs (https://github.com/python-attrs/attrs/blob/main/setup.py#L17), except for `repository` which is a poetry built-in.

Add project URLs for changelog, issues and code

---

HISTORY.rst
docs/structuring.rst
src/cattr/converters.py
src/cattr/dispatch.py
src/cattr/errors.py
src/cattr/gen.py
tests/test_function_dispatch.py
tests/test_generics.py
tests/test_structure.py
tests/test_structure_attrs.py

Resolves https://github.com/Tinche/cattrs/issues/138
If an attrs class has defined a converter with  `attr.ib`, fallback that instead if dispatching to cattrs converters fails to find a handler.
Also, add a new option `prefer_attrib_converters` to use them if defined instead of handlers registered in cattrs.

Structure using the value of attr.ib converter, if defined

---

tests/test_preconf.py
tox.ini

1. Install `poetry` inside tox not to require external install of poetry.
2. Support passing additional args to pytest via tox.
3. <del>Skip respective `test_preconf` tests when deps are missing instead of failing.</del> <ins>Move test-related imports to test functions.</ins>
4. <del>Skip bson tests if incompatible `bson` module from pymongo is installed.</del>

Various test suite compatibility improvements

---

CONTRIBUTING.rst
HISTORY.rst
docs/installation.rst
pyproject.toml

Those should now point to python-attrs/cattrs
Fixes #186

Fix old references to Tinche/cattrs

---

tests/test_preconf.py

Check whether 64-bit time_t is supported. If not, make sure to limit
timestamps to 32 bits.

Fix test with 32-bit time_t

---

HISTORY.rst
src/cattr/_compat.py
src/cattrs/gen.py
tests/metadata/__init__.py

Fixes #218
(EDIT 3.2.) I added tests describing the following behaviours:
* attribute annotated by a bare lower-case generic - `dict`, `frozenset`, `list`, `set`, `tuple`
* attribute annotated by a `typing.` upper-case generic with 1 type parameter, which can itself be a lower-case generic - this excludes sets and tuple
* attribute annotated by `typing.Tuple` with variadic lower-case generics
Cheers,
Libor

Fix py37-38 structuring of mixed typing/regular generics

---

HISTORY.rst

Sorry, I messed up the links to issues resolved - they display incorrectly and look like in the screenshot below:

Fix issue links in HISTORY

---

HISTORY.rst
src/cattrs/gen.py
tests/test_converter_inheritance.py

There are Generic types in the typing modules
from which you can inherit in your own classes
which do not have an __parameters__ attribute,
such classes are now ignored making
gen._generate_mapping effectively a no-op
in case the class do not have an __parameters__
attribute.
As https://github.com/ilevkivskyi/typing_inspect/blob/8f6aa2075ba448ab322def454137e7c59b9b302d/typing_inspect.py#L405
is showing there are also cases where __parameters__
could be None, so I test for both cases, that it
is None or that it does not exist.
See Also:
https://github.com/python-attrs/cattrs/issues/217

Fix  __parameters__ access in gen._generate_mapping

---

HISTORY.rst
src/cattr/converters.py
tests/test_structure_attrs.py

Literal allows Enum values to be specified, however, the Literal check did not account for that:
```py
import cattrs, enum
from typing import Literal
class A(enum.Enum):
BLA = 1
BLAA = 2
@attrs.define
class Works:
a: A
@attrs.define
class Broken:
a: Literal[A.BLA]
print(cattrs.structure({"a": 1}, Works))   # Works(a=<A.BLA: 1>)
print(cattrs.structure({"a": 1}, Broken))  # Exception: 1 not in literal typing.Literal[<A.BLA: 1>]
```
(This would work if A would also inherit from int.)
It makes sense that if cattrs already accepts 1 as a valid enum value, the Literal check should go by value as well.
This PR fixes this bug, ~~and also slightly modifies an existing test to make sure that `Literal[1, Literal[2]]` is handled like `Literal[1, 2]`.~~ *(Edit: the last part is not correctly supported …

Fix handling of Enums in Literal types

---

tests/test_preconf.py

On Windows, `datetime.fromtimestamp` only seems to support positive values, cause test_msgpack in test_preconf to fail with OSError.

fix test failure on Windows

---

HISTORY.rst
src/cattr/_compat.py
src/cattr/converters.py

Fixes #226
Fixes #214
Now, all tuples are unstructured to `list` by default.
<strike>Needs a changelog entry and</strike> we are ready to go!

Fix inconsistent `tuple/typing.Tuple` unstructuring

---

HISTORY.rst
docs/customizing.rst
docs/structuring.rst
src/cattrs/errors.py
src/cattrs/gen.py
tests/metadata/test_genconverter.py
tests/test_gen_dict.py

When `forbid_extra_keys` is actived, I would like to be able to try-except that specific Problem (here `ForbiddenExtraKeyError`) instead of any `Exception`.
The unit tests also gain a little more percition through that change.

For `forbid_extra_keys` raise custom `ForbiddenExtraKeyError`

---

src/cattrs/gen.py

I notice that `override` and `make_dict_unstructure_fn` got missing annotations. 
This PR address this.
Signed-off-by: Aaron Pham <29749331+aarnphm@users.noreply.github.com>

fix: missing annotations from `override` and `make_dict_unstructure_fn`

---

poetry.lock
tests/test_validation.py

The ValueError from InValidator has been augmented to include a lot of other structured information that, for simplicity, we can ignore in the test.
**Motivation**
In the [nixpkgs](https://github.com/NixOS/nixpkgs) package manager, `attrs` has been updated, and it becomes necessary to update all of its consumers.

Update attrs to 22.1.0 and fix test.

---

src/cattrs/converters.py
tests/test_structure.py

When structuring a heterogeneous tuple, if the input has too few or many elements, this PR now raises an error. The error is a `ValueError` in non-detailed validation.
Two existing tuple-structuring tests had to be fixed (in the zero-element case).
Fixes #57

Raise on input/tuple-args length mis-match

---

pyproject.toml

Related to #202 and https://github.com/python-poetry/poetry/issues/4938 - looks like poetry 1.2.0 depends on poetry-core 1.1.0, so I assume the 'groups' feature is present in poetry-core 1.1.0 and that version would be a good one to use.

Fix imprecise dependency on poetry-core

---

HISTORY.rst
src/cattrs/gen.py
tests/test_gen_dict.py

Certain uses of `typing.Literal` or `typing.Annotated` cause syntax errors in generated code. (Related: https://github.com/python-attrs/cattrs/issues/277)
In the case of annotated types (from 3.7 typing_extensions), I get the following syntax error:
```
eval(compile(script, "", "exec"), globs)
E     File "<string>", line 17
E       raise IterableValidationError('While structuring typing.Dict[typing_extensions.Annotated[str, <class 'housecats.annotations.sanitization.PIIAnnotation'>], vnxpy.jobs.types.leaf.AssigneeRemoval]', errors, __cattr_mapping_cl)
E                                                                                                                     ^
E   SyntaxError: invalid syntax
```
As mentioned in #277 by @Tinche; we _could_ escape quotes manually but using `repr()` …

Fix: GenConverter syntax errors with certain types

---

src/cattrs/converters.py
src/cattrs/disambiguators.py
src/cattrs/gen.py

Fix bad merge and update annotations from #288
Address comments type syntax to newer syntax.

chore: update annotations

---

HISTORY.rst
docs/validation.rst
src/cattrs/converters.py
src/cattrs/gen.py
tests/test_validation.py

Fix #301 by moving from `__note__` to `__notes__`. We could set a minimum `exceptiongroup` version, though if we do that, I think it will enable dev releases even after a non dev release is made.

fix: use __notes__ instead of __note__

---

docs/preconf.md

This PR just fixes a misspell in the documentation for  converter preconfigured for CBOR - "arguemnt" -> "argument"

Fix a misspell in documentation for CBOR converter

---

docs/structuring.md

```diff
- All other unions a require a disambiguation function.
+ All other unions require a disambiguation function.
```

Fix minor typo

---

HISTORY.md
src/cattrs/preconf/bson.py
src/cattrs/preconf/cbor2.py
src/cattrs/preconf/json.py
src/cattrs/preconf/msgpack.py
src/cattrs/preconf/orjson.py
src/cattrs/preconf/pyyaml.py
src/cattrs/preconf/tomlkit.py
src/cattrs/preconf/ujson.py
tests/test_preconf.py

Allow overriding unstruct_collection_overrides

---

src/cattrs/preconf/bson.py
src/cattrs/preconf/cbor2.py
src/cattrs/preconf/json.py
src/cattrs/preconf/msgpack.py
src/cattrs/preconf/orjson.py
src/cattrs/preconf/pyyaml.py
src/cattrs/preconf/tomlkit.py
src/cattrs/preconf/ujson.py

This isn't really a material improvement but Pyright does not infer the type of un-annotated parameters to be `Any` and produces an error at call site.

Increase type coverage for Pyright's benefit

---

HISTORY.md
docs/structuring.md
docs/unstructuring.md
src/cattrs/_compat.py
src/cattrs/converters.py
tests/test_converter.py
tests/test_generics.py
tests/test_structure.py
tests/test_structure_attrs.py
tests/untyped.py

```
Python==3.10.4
attrs==22.2.0
cattrs==23.1.0.dev0@98ca33ab7
```
Current head version of `cattrs` work normally to unstructure `deque`, but fails to structure obj into `deque` (or generic `deque`)
Minimal reproducible example:
```python
@define
class C:
x: int
y: int
a = deque((C(x=x, y=y) for x, y in zip(range(10), range(10, 20))))
print(cattrs.unstructure(a))
b = ({"x": x, "y": y} for x, y in zip(range(10), range(10, 20)))
print(cattrs.structure(b, deque[C]))
```
`deque` is a battery-included std container, so I think it's sensible to add a default structure hook for it.
Some notable facts:
```python
print(issubclass(deque, list))
print(issubclass(defaultdict, dict))
```
I once want to also add a structure hook for `defaultdict`, but I thought it's probably difficult to give a factory …

Add unstructuring and structuring support for `deque` in standard lib

---

pyproject.toml

Quick fix #369 - this is now required on 3.10 due to Required/NotRequired usage.

fix: missing dependency on Python 3.10

---

HISTORY.md
src/cattrs/v.py

Pyright expects `typing.Type` to be parameterised and reports that the function's type is unknown.

Fix type checker error

---

src/cattrs/_compat.py

Unsure if this worked in MyPy but Pyright failed to resolve the base of `BaseValidationError` subclasses leading to hard to trace type errors in custom note attributes from failing to narrow Iterable and ClassValidationError unions.

Make `BaseValidationError` base static in Python < 3.11

---

src/cattrs/_compat.py
src/cattrs/gen/typeddicts.py
tests/_compat.py
tests/test_baseconverter.py
tests/test_converter.py
tests/test_gen_dict.py
tests/test_generics.py
tests/test_optionals.py
tests/test_structure_attrs.py
tests/test_typeddicts.py
tests/test_unions.py
tests/test_unstructure_collections.py

Type checkers are unable to interpret `sys.version_info` aliases and generate unions between Python version branches.  If either branch depends on packages which are not installed the union might be reduced to an unknown or any type.
Follow-up from https://github.com/python-attrs/cattrs/pull/379 (Pyright would merge the two branches).

Make Python versions known statically

---

.github/workflows/main.yml

While investigating https://github.com/python/typing_extensions/issues/230 and preparing #384, I tried running cattrs's CI on my fork via workflow-dispatch. This was made a little more complicated by the fact that the "upload coverage to codecov" step always seems to fail when the workflow is run on a fork

Don't try to upload coverage if CI is run via workflow dispatch on a fork

---

.github/workflows/main.yml

This will make it easier to see in #384 which tests (if any) are actually failing on which Python versions -- currently the codecov failures are just leading to all jobs being cancelled in CI

Don't cancel all jobs in CI if one job fails

---

HISTORY.md
src/cattrs/preconf/orjson.py

`bytes` is not the only input type `orjson.loads` allows.

Broaden method type definition for preconf orjson converter.

---

src/cattrs/converters.py

The intended first argument to `getattr` should be the exception in question.

Fix typos for notes getattr calls

---

HISTORY.md
src/cattrs/errors.py
tests/test_validation.py

Certain test runners (in my case, Django's `RemoteTestRunner`) pickle the exceptions raised to accumulate them from multiple processes.
For exceptions with `AttributeValidationNote` and/or `IterableValidationNote` attached, because we have overridden `__new__` on these classes, pickle cannot correctly unpickle them with the required arguments. For this use case, exceptions being pickable is necessary to accumulate errors with the `multiprocessing` setup.
This implements [`__getnewargs__`](https://docs.python.org/3/library/pickle.html#object.__getnewargs__) to fix this problem.

Make validation notes picklable.

---

tests/typeddicts.py

Reduce the range of generated `datetime` instances to values valid for 32-bit `time_t` range, as otherwise multiple tests fail with errors such as:
FAILED tests/test_typeddicts.py::test_simple_roundtrip - OverflowError: timestamp out of range for platform time_t
This is based on an earlier fix for `test_preconf.py`, see a0e56f43f061c43814d6f938833d1c325ed61525
and c58028789454fc7a9b459b94c214cab2ab1acb81.
Originally reported as https://bugs.gentoo.org/912187.

Fix typeddict tests on systems with 32-bit time_t

---

docs/strategies.md
src/cattrs/strategies/__init__.py
src/cattrs/strategies/_class_methods.py
tests/strategies/test_class_methods.py

feat: strategy for using class methods

---

HISTORY.md
src/cattrs/converters.py
tests/test_converter.py

This appears to be caused by a thinko in #391, this fixes it again.

Use the un-underscored name if no alias attribute is there.

---

HISTORY.md
Makefile
src/cattrs/_compat.py
src/cattrs/preconf/orjson.py
tests/test_baseconverter.py
tests/test_gen.py
tests/test_generics.py
tests/test_validation.py

Fix non-generic protocols

---

tests/strategies/test_tagged_unions.py

I've converted some project which uses cattrs from attrs to dataclasses, but that failed because the union dismbiguator doesn't support dataclasses yet (https://github.com/python-attrs/cattrs/issues/426#issuecomment-1731787790). So I used the opportunity to convert the code to the new tagged union strategy which is much nicer than the disambiguation stuff anyway. One case looks like the test added in this PR, which failed too (cattrs  v23.1.2). Looking into it I saw that the problem has been fixed in main by commit b25a25800f245d4504f8d9aaaa90faeca3e4adbb. So I'm awaiting a new release, but in the meantime thought this regression test might be helpful.

Add a regression test for a nested tagged union scenario

---

HISTORY.md
src/cattrs/_compat.py
src/cattrs/dispatch.py

Import typing_extensions.TypeAlias only on python < 3.11

---

HISTORY.md
src/cattrs/_compat.py
tests/test_structure_attrs.py

...or libraries that still support Python 3.7
would close #460

structure typing_extension.Literal to support old code

---

HISTORY.md
src/cattrs/strategies/_subclasses.py
src/cattrs/strategies/_unions.py

Using Converter instead of BaseConverter as one of the arguments to union_strategy allows more strategies to be passed. Specifically, the configure_tagged_union strategy currently requires a Converter according to its typing.

Fix include_subclass union_strategy typing

---

pyproject.toml

`msgspec` is [only supported on CPython](https://github.com/jcrist/msgspec/issues/22#issuecomment-1349049009). This creates an issue when installing with: `pdm install -G :all`.

Don't install `msgspec` on PyPy

---

docs/strategies.md

While reading the docs, I just noticed this small typo, so thought I would submit a quick PR.

Fix typo in strategies.md

---

HISTORY.md
src/cattrs/gen/_generics.py
tests/test_generics_696.py

This adds support for TypeVars with default values, as defined in [PEP 696](https://peps.python.org/pep-0696/).  This PEP was [recently recommended by the typing council to be accepted](https://github.com/python/typing-council/issues/12#issuecomment-1935231468), and is currently [already available](https://github.com/python/typing_extensions/blob/06b23e3f05fd0f929dbaea17ae51621dcc8434ab/src/typing_extensions.py#L1435-L1443) via `typing_extensions.TypeVar` (see test case)
Essentially if you have a generic class:
```python
from attrs import define
from typing import TypeVar
T = TypeVar("T")
@define
class C(Generic[T]):
a: T
```
You must specify the generic type to use it:
```python
@define
class Foo:
c: C[str]  # C.a = str
```
While this causes is [an …

Add cattrs support for TypeVar with default (PEP696)

---

src/cattrs/gen/_generics.py

When implementing PEP 696 (default values for TypeVars, ParamSpecs and TypeVarTuples, we decided to implement the PEP slightly differently from the prototype that existed in `typing_extensions`. Specifically:
- With the old implementation in `typing_extensions`:
- If you passed `default=None` when constructing a TypeVar, the `__default__` attribute would be set to `types.NoneType`
- If you did not pass a value to the `default=` parameter, the `__default__` attribute would be set to `None`
- With the new implementation in CPython:
- If you pass `default=None` when constructing a TypeVar, the `__default__` attribute is set to `None`
- If you do not pass a value to the `default=` parameter, the `__default__` attribute is set to the new sentinel object `typing.NoDefault`.
- The new …

Make detection of TypeVar defaults robust to the CPython PEP-696 implementation

---

README.md

Here's a first attempt – let's iterate.

Pimp README

---

HISTORY.md
src/cattrs/converters.py

Change type of unstruct_collection_overrides from Mapping[type, Callable] to Mapping[type, UnstructureHookT] in Converter.__init__.

Converter parameter type hints

---

src/cattrs/preconf/bson.py
src/cattrs/preconf/json.py
src/cattrs/preconf/msgpack.py
src/cattrs/preconf/msgspec.py
src/cattrs/preconf/orjson.py
src/cattrs/preconf/pyyaml.py
src/cattrs/preconf/ujson.py
tests/__init__.py
tests/test_defaultdicts.py
tests/test_disambiguators.py
tests/test_gen_dict.py
tests/test_preconf.py
tests/test_tests.py
tests/test_tuples.py
tests/test_typeddicts.py
tests/test_unstructure.py
tests/typed.py
tests/typeddicts.py
tests/untyped.py

- **Improve cols coverage**
- **Test the tests**
- **Improve typeddict coverage**
- **Improve disambiguators coverage**
- **preconf: test bare dicts**
- **test_preconf: always include bools and ints**

More tests

---

docs/defaulthooks.md

docs/defaulthooks: add note on TypedDict Required/NotRequired with `from __future__ import annotations`

---

tests/test_disambiguators.py

See python/cpython#131933. Python does not guarantee that running `Union[A, B]` twice gives the same object back. This test is currently broken in Python 3.14 main.

Fix reliance on unspecified behavior in test_disambiguators.py

---

HISTORY.md
src/cattrs/gen/_generics.py
tests/test_converter_inheritance.py

Fixes #654 
The first commit reproduces the error `AttributeError: type object 'Iterable' has no attribute '__parameters__'`.
I will follow up with the actual fix.

Fix structuring of attrs class that inherit from typing/collections.abc generic type aliases

---

HISTORY.md
src/cattrs/converters.py
src/cattrs/gen/__init__.py
src/cattrs/gen/typeddicts.py
tests/test_converter.py

Based on the discussion in #596, adds a `use_alias` argument to `Converter` (similar to `forbid_extra_keys') whose value is taken as default when structuring/unstructuring without specifying the corresponding argument to the method calls.

Extract use_alias from converter by default

---

docs/migrations.md

The change was moved to version 25.1.0 from version 24.2.0 in #618 but the migration entry was not updated accordingly.

DOCS: Fix version for "default structure hook fallback factory" migration

---

HISTORY.md
src/cattrs/errors.py
tests/test_errors.py
tests/test_typeddicts.py

`BaseExceptions` subclasses need all parameters of their `__init__` methods to be passed to `BaseExceptions.__init__`, see [`BaseException.args`](https://docs.python.org/3.9/library/exceptions.html#BaseException.args) for that.
This MR will correct the `super().__init__` call.
This will also make the Exceptions pickable, which I need for a cache and for multiprocessing.
The interface does not change with this MR.
But for `ForbiddenExtraKeysError` I moved the
"Extra fields in constructor for {self.cl.__name__}: {', '.join(self.extra_fields)}"
string to `__str__` instead of storing it in the object as attribute. As this is a fixed string for the class (which means it does not need be stored) and will be used when actually `""` was passed to the constructor, I think this makes more sense.

(errors) Correctly set `BaseException.args` and make them pickable

---

docs/customizing.md

Hey @Tinche 👋 
I was just reviewing the docs, and noticed the `get_args` import missing, which I think it adds to have. I put the example in the editor and it complained about `Any` and `Callable` too (which I guess is fair). I thought I'd send in the clean up.

Added missing imports to hook factory decorator example.
