- bench/bench.py
- cattr/converters.py
- cattr/function_dispatch.py
- cattr/multistrategy_dispatch.py
Hi,
I started using cattrs, but noticed it was slower than my previous hand-rolled code, so I added a micro-benchmark and performed some easy optimizations based on it. Please see the commit messages for details.
There are more optimizations possible of course, hopefully someone else will try :)
Also, I only looked at the dict-based code. Tuples are faster, but I use dicts for extensibility.
> Some easy optimizations

- HISTORY.rst
- cattr/converters.py
- docs/structuring.rst
- tests/metadata/test_roundtrips.py
- tests/test_unstructure.py
Please see the commit messages. Note that the last commit is a breaking change.
> Hide internal details and remove some dynamism

- HISTORY.rst
- cattr/converters.py
A few more things I noticed. Please see the commit messages for details.
> Some more small optimizations

- docs/structuring.rst
- src/cattr/converters.py
- src/cattr/disambiguators.py
> strip leading underscores from attributes so can be structured.

- MANIFEST.in
- src/cattr/generation.py
Additionally made a small improvement to the type signature of a function in `generation.py`
Addresses #60
> added py.typed to src and distribution

- .travis.yml
- HISTORY.rst
- setup.py
- src/cattr/_compat.py
- tests/_compat.py
- tox.ini
> Add support for python 3.8

- src/cattr/converters.py
- tests/test_dataclasses.py
https://github.com/Tinche/cattrs/issues/43
Minor fixes to converters.py for some basic conversion smoke tests.
> Add smoke tests for nested attrs-dataclasses

- pyproject.toml
- src/cattr/disambiguators.py
- src/cattr/gen.py
- tests/_compat.py
- tests/metadata/test_genconverter.py
- tests/test_dict_generation.py
- tests/test_disambigutors.py
- tests/test_unstructure_collections.py
- tox.ini
Changes:
* Updated `tox -e lint` to run isort
* Updated isort settings to use the "black" profile
* Ran isort
> cleanup: run isort and add to tox linter check

- src/cattr/converters.py
- tests/test_structure_attrs.py
> Fix Literal[...] with more than one item

- docs/customizing.rst
- tests/metadata/test_genconverter.py
> Remove _cattr_forbid_extra_keys from docs and tests

- src/cattr/preconf/bson.py
- src/cattr/preconf/json.py
- src/cattr/preconf/msgpack.py
- src/cattr/preconf/orjson.py
- src/cattr/preconf/pyyaml.py
- src/cattr/preconf/tomlkit.py
- src/cattr/preconf/ujson.py
This fixes missing imports of preconf converters (see: #308)
> Fix missing imports of preconf converters

- docs/structuring.md
This might not be the best way to reference it, but I do believe that there should be a reference to Strategies somewhere in this section.
> Add reference to Strategies

- docs/usage.md
Providing examples as discussed in https://github.com/python-attrs/cattrs/issues/347
Note: I can tell there is some formatting applied to the existing docs, but I couldn't find guidance in `CONTRIBUTING.md` or a clear command in `Makefile` - but happy to take some pointers and add those too.
Hope this is along the lines we discussed!
> fallback key name usage example docs

- HISTORY.md
- src/cattrs/v.py
- tests/test_v.py
> Added format_exception to recursive calls of transform_error. [#389]

- docs/index.md
- docs/recipes.md
Hi @Tinche,
here's a first draft for the "Recipes" page you suggested in #489.
Let me know what you think and what needs to be adapted. Of course feel free to adjust examples and text as you like.
BTW: Should we add some tests for the recipes, or is there some automatic doc testing already in place (haven't yet looked too much into the repo mechanisms, tbh).
> Recipes for initializer selection

- tests/strategies/test_include_subclasses.py
> Add test for #430

- tox.ini
> Fix tox shenanigans

- .github/workflows/main.yml
And get rid of the annoying warnings in the CI summaries.
> Switch to (up|down)load-artifact@v4

- tests/test_baseconverter.py
this is a follow up commit to 96ed9a1c972814c379f9ea8faa3413aacd4ce6cb
> Stop generating nan values in tests to work with latest attrs (round 2)

- src/cattrs/converters.py
- src/cattrs/errors.py
- src/cattrs/gen/__init__.py
- tests/test_disambiguators.py
- tests/test_generics.py
- tests/test_unions.py
- tests/test_validation.py
Let's get our missing statements count to below 10.
> More test coverage
